builds:
  -
    main: ./cmd/gitstrap/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      # @todo #4:15min Build date is missing.
      #  Let's add build date in ISO timestamp format 
      #  to environment variables from travis deploy script
      #  to use it here as `main.buildDate` X ldflag.
      - -s -w -X "main.buildVersion={{.Env.TRAVIS_TAG}}{{.Env.TRAVIS_BUILD_NUMBER}}" -X "main.buildCommit={{.Env.TRAVIS_COMMIT}}"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brew:
  github:
    owner: g4s8
    name: .tap
  commit_author:
    name: goreleaser
    email: g4s8.public+tap@gmail.com
  homepage: "https://github.com/g4s8/gitstrap"
  folder: Formula
  dependencies:
    - git
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
