---
docker:
  image: "g4s8/gorultor:alpine"
env:
  PATH: /usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  CGO_ENABLED: 0
merge:
  script:
    - "mkdir -pv /home/r/go/src/github.com/g4s8"
    - "ln -snv $PWD /home/r/go/src/github.com/g4s8/gitstrap"
    - "cd /home/r/go/src/github.com/g4s8/gitstrap"
    - "go env"
    - "go get -t ./..."
    - "go build -o /dev/null ."
    - "go build -o /dev/null ./cmd/gitstrap"
    - "go test ."
    - "golangci-lint run"
    - "pdd --source=$(pwd) --verbose --file=/dev/null"
    - "gitlint"
  fast-forward: "no"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
architect:
  - "g4s8"
